<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JSUjo-PC" ignored="0" name="Rectangle Health(failed)" tests="3" failures="3" timestamp="13 Nov 2019 21:36:02 GMT" time="33.108" errors="0">
  <testcase name="addNewVault" time="11.59" classname="com.rh.testCases.TC_AddVault_003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.rh.testCases.TC_AddVault_003.addNewVault(TC_AddVault_003.java:58)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- addNewVault -->
  <testcase name="loginDDT" time="4.063" classname="com.rh.testCases.TC_LoginDDT_004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.rh.testCases.TC_LoginDDT_004.loginDDT(TC_LoginDDT_004.java:42)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase name="loginDDT" time="3.972" classname="com.rh.testCases.TC_LoginDDT_004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.rh.testCases.TC_LoginDDT_004.loginDDT(TC_LoginDDT_004.java:42)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- Rectangle Health(failed) -->
